### PR TITLE
Pset1+2+3+4

### PR DESCRIPTION
**Pull request by samina-mulani**

### CODE REVIEW

**Comment by twitu** [comment]
create pset1 directory to store these files.

**Comment by samina-mulani** [comment]
Have created Pset1 directory and have also added Pset2 and Pset3

**Comment by siddhantkhandelwal** [comment]
Nice work!
Just a few suggestions:
Update the README.md file with your progress.

**Comment by siddhantkhandelwal** [comment]
@samina-mulani There are merge conflicts in the Pull Request.
Refer: https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts

**Pull request merged**
